Repository spatialos/gdk-for-unity-shared-ci, pull requests merged in 2019-09, with the labels that each got.

#57 Update `gdk.pinned` format
  tools/ReleaseTool/PrepCommand.cs
Labels: jira/UTY, size/XS

#58 Publish packages during release pipeline
  .buildkite/release.steps.yaml
  ci/docker/publish-packages-entrypoint.sh
  ci/docker/publish-packages.Dockerfile
  ci/publish-packages.sh
Labels: jira/no-ticket, size/L

#59 Enabling XCode build
  scripts/build-worker.sh
Labels: jira/no-ticket, size/S
