Repository spatialos/gdk-for-unity-shared-ci, pull requests merged in 2020-06, with the labels that each got.

#73 Pin Linter
  ci/docker/lint/Dockerfile
Labels: jira/no-ticket, size/XS

#75 New Buildkite instrumentation format
  ci/build-test.sh
  ci/common.sh
  ci/docker/entrypoint.sh
  ci/docker/premerge.Dockerfile
  ci/lint.sh
  ci/prepare-release.sh
  ci/publish-packages.sh
  ci/release.sh
  ci/sync-dependencies.sh
  scripts/build-worker.sh
  scripts/lint.sh
  scripts/pinned-tools.sh
Labels: jira/no-ticket, size/XL

#76 Add secrets to publishing Docker image for China NPM registry
  ci/docker/publish-packages-entrypoint.sh
  ci/docker/publish-packages.Dockerfile
  ci/publish-packages.sh
Labels: jira/no-ticket, size/S
