Repository spatialos/gdk-for-unity-shared-ci, pull requests merged in 2020-01, with the labels that each got.

#68 Fix release tool nits
  tools/ReleaseTool/PrepCommand.cs
  tools/ReleaseTool/ReleaseCommand.cs
Labels: jira/no-ticket, size/S

#66 Add buildkite pipeline + script for updating macosx dependencies in gcs
  .buildkite/update-deps.definition.yaml
  .buildkite/update-deps.steps.yaml
  ci/sync-dependencies.sh
Labels: jira/no-ticket, size/M

#69 Sync dependencies using .NET 3 and expand to multi-platform
  ci/sync-dependencies.sh
  dependencies.pinned
Labels: jira/DOTNET, size/S
